---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible -qq

script:
  # Test for Syntax
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --syntax-check
  # Test for Failure
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --connection=local
    --sudo
  # Test for Idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --connection=local
    --sudo
    | grep -q 'changed=0.*failed=0'
  # Test for Succuss
  - >
    sudo service rtorrent status
    | grep -q "running"
  - >
    ls /home/rtorrent/download
    > /dev/null
  - >
    ls /home/rtorrent/session
    > /dev/null
  - >
    ls /home/rtorrent/watch
    > /dev/null
