---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Test for Syntax
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --syntax-check --sudo
  # Test for Failure
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --connection=local --sudo
  # Test for Idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
  # Test for Succuss
  - >
    sudo service rtorrent status
    | grep -q "running"
  - >
    ls /home/rtorrent/download
    > /dev/null
  - >
    ls /home/rtorrent/session
    > /dev/null
  - >
    ls /home/rtorrent/watch
    > /dev/null
  - >
    grep -q "scgi_port = 127.0.0.1:5001" /home/rtorrent/.rtorrent.rc

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
