---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible and molecule
  - pip install ansible molecule

  # Check ansible version
  - ansible --version

  # Check ansible version
  - molecule --version

script:
  #use a differnet scenrario make a delegated scneario for the cloud
  - molecule --debug test --scenario-name travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
